# Generated by Django 3.2.20 on 2023-07-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerWorkflowSystem', '0002_auto_20230705_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialdata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='financialdata',
            name='expenditure',
        ),
        migrations.AddField(
            model_name='financialdata',
            name='expenses',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='financialdata',
            name='month',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='income',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
