# Generated by Django 3.2.20 on 2023-07-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerWorkflowSystem', '0003_auto_20230705_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
