# Generated by Django 3.2.20 on 2023-07-05 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerWorkflowSystem', '0005_auto_20230706_0140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialdata',
            old_name='Expenses',
            new_name='expenses',
        ),
        migrations.RenameField(
            model_name='financialdata',
            old_name='Income',
            new_name='income',
        ),
        migrations.RenameField(
            model_name='financialdata',
            old_name='Month',
            new_name='month',
        ),
    ]
