# Generated by Django 3.2.20 on 2023-07-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerWorkflowSystem', '0006_auto_20230706_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='graphs/'),
        ),
    ]
