# Generated by Django 3.2.20 on 2023-07-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerWorkflowSystem', '0008_alter_customer_graph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='graph',
        ),
    ]
